# Generated by Django 4.2.3 on 2023-07-08 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('nombre', models.CharField(max_length=100)),
                ('cedula_ruc', models.CharField(max_length=20, unique=True)),
                ('turno', models.AutoField(primary_key=True, serialize=False)),
                ('prioridad', models.IntegerField(choices=[(1, 'Prioridad 1'), (2, 'Prioridad 2'), (3, 'Prioridad 3')])),
                ('servicios', models.IntegerField(choices=[(1, 'Box 1'), (2, 'Box 2'), (3, 'Box 3')])),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('atendido', models.BooleanField(default=False)),
            ],
        ),
    ]
