# Generated by Django 4.2.3 on 2023-07-08 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnero', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='prioridad',
            field=models.IntegerField(choices=[(1, 'Baja'), (2, 'Media'), (3, 'Alta')]),
        ),
    ]
