# Generated by Django 4.2.3 on 2023-07-08 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turnero', '0003_empleado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Empleado',
        ),
    ]
